stages: [test, package, build]

run_tests:
  stage: test
  image: maven:3.6-jdk-11
  script:
    - mvn test

package_application:
  stage: package
  image: maven:3.6-jdk-11
  script:
    - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/*.jar

build_and_push_image:
  stage: build
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker build -t $DOCKERHUB_USERNAME/my_application:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKERHUB_USERNAME/my_application:$CI_COMMIT_SHORT_SHA
